# Generated by Django 6.0.7 on 2026-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='facility_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='facility_gstin_snapshot',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='facility_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='party_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='party_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='facility_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='facility_gstin_snapshot',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='facility_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
