# Generated by Django 6.0.7 on 2026-07-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_remove_historicalinvoice_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='rent_run',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rent_run',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='rent_run_line',
        ),
    ]
