# Generated by Django 6.0.7 on 2026-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_bank_account_no_facility_bank_ifsc_and_more'),
        ('invoicing', '0004_historicalpayment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('facility', 'invoice_number')},
        ),
    ]
