# Generated by Django 6.0.7 on 2026-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_alter_historicalinvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
