# Generated by Django 6.0.7 on 2026-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoiceline_quantity_invoiceline_rate_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
