# Generated by Django 6.0.7 on 2026-08-01 00:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_historicalinvoice_last_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='document_type',
            field=models.CharField(choices=[('TAX_INVOICE', 'Tax Invoice'), ('BILL_OF_SUPPLY', 'Bill of Supply')], default='TAX_INVOICE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='exemption_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='financial_year',
            field=models.CharField(blank=True, db_index=True, max_length=7),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('TAX_INVOICE', 'Tax Invoice'), ('BILL_OF_SUPPLY', 'Bill of Supply')], default='TAX_INVOICE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exemption_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='financial_year',
            field=models.CharField(blank=True, db_index=True, max_length=7),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='charge_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('LOADING_UNLOADING', 'Loading/Unloading'), ('TRANSPORT', 'Transport'), ('WEIGHING', 'Weighing'), ('OTHER', 'Other')], default='RENT', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='sac_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
