# Generated by Django 6.0.7 on 2026-07-24 21:40

from django.db import migrations

OLD_STATUS = 'RECEIVED'
NEW_STATUS = 'POSTED'


def received_to_posted(apps, schema_editor):
    """standing.md §1: GRN statuses are DRAFT -> POSTED (+ CANCELLED)."""
    for model_name in ('GRN', 'HistoricalGRN'):
        model = apps.get_model('inventory', model_name)
        model.objects.filter(status=OLD_STATUS).update(status=NEW_STATUS)


def posted_to_received(apps, schema_editor):
    for model_name in ('GRN', 'HistoricalGRN'):
        model = apps.get_model('inventory', model_name)
        model.objects.filter(status=NEW_STATUS).update(status=OLD_STATUS)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_grn_status_alter_historicalgrn_status'),
    ]

    operations = [
        migrations.RunPython(received_to_posted, posted_to_received),
    ]
