# Generated by Django 6.0.7 on 2026-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_migrate_grn_received_to_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
