# Generated by Django 6.0.7 on 2026-07-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_grn_loading_charge_historicalgrn_loading_charge'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='chamber_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.chamber'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='floor_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.floor'),
        ),
        migrations.AddField(
            model_name='lot',
            name='chamber_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='locations.chamber'),
        ),
        migrations.AddField(
            model_name='lot',
            name='floor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='locations.floor'),
        ),
    ]
