# Generated by Django 6.0.7 on 2026-07-25 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_lot_location_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='grn',
            name='bilty_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='grn',
            name='inward_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='loading_unloading_rate_per_bag',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='grn',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='grns/'),
        ),
        migrations.AddField(
            model_name='grn',
            name='preservation_rate_per_bag_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='grn',
            name='transporter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='bilty_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='inward_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='loading_unloading_rate_per_bag',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='pdf_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='preservation_rate_per_bag_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='transporter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='special_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lot',
            name='special_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
