# Generated by Django 6.0.7 on 2026-07-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_grn_bill_no_grn_bilty_no_grn_inward_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='historicalgrn',
            name='pdf_file',
        ),
    ]
