# Generated by Django 6.0.7 on 2026-07-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_grn_pdf_file_remove_historicalgrn_pdf_file'),
        ('locations', '0002_restructure_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='block_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.block'),
        ),
        migrations.AddField(
            model_name='lot',
            name='block_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='locations.block'),
        ),
    ]
