# Generated by Django 6.0.7 on 2026-07-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_historicallot_block_ref_lot_block_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='loading_charge_mode',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PER_UNIT', 'Per Unit')], default='FLAT', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='loading_charge_mode',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PER_UNIT', 'Per Unit')], default='FLAT', max_length=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='unit',
            field=models.CharField(default='BAGS', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='unit',
            field=models.CharField(default='BAGS', max_length=20),
        ),
    ]
