# Generated by Django 6.0.7 on 2026-07-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_grn_loading_charge_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='loading_charge_invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='loading_charge_invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
