# Generated by Django 6.0.7 on 2026-07-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_bank_account_no_facility_bank_ifsc_and_more'),
        ('inventory', '0011_grn_loading_charge_invoiced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='facilities.facility'),
        ),
    ]
