# Generated by Django 6.0.7 on 2026-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_bank_account_no_facility_bank_ifsc_and_more'),
        ('inventory', '0012_alter_sequence_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='grn_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalgrn',
            name='grn_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='grn',
            unique_together={('facility', 'grn_number')},
        ),
    ]
