# Generated by Django 6.0.7 on 2026-07-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_bank_account_no_facility_bank_ifsc_and_more'),
        ('inventory', '0013_alter_grn_grn_number_alter_historicalgrn_grn_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('facility', 'lot_number')},
        ),
    ]
