# Generated by Django 6.0.7 on 2026-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_lot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
