# Generated by Django 6.0.7 on 2026-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_grn_last_emailed_at_historicalgrn_last_emailed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='legacy_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalgrn',
            name='legacy_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='legacy_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lot',
            name='legacy_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
