# Generated by Django 6.0.7 on 2026-08-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_state_code'),
        ('inventory', '0016_add_legacy_ref'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sequence',
            name='financial_year',
            field=models.CharField(blank=True, db_index=True, max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('facility', 'sequence_type', 'financial_year')},
        ),
    ]
