# Generated by Django 6.0.7 on 2026-08-01 21:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_sequence_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockAdjustment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('qty_delta', models.IntegerField()),
                ('qty_before', models.PositiveIntegerField()),
                ('qty_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('NOT_FOUND', 'Not Found'), ('SPOILAGE', 'Spoilage'), ('COUNT_CORRECTION', 'Count Correction'), ('FOUND_EXTRA', 'Found Extra'), ('MIGRATION_OPENING_BALANCE', 'Migration Opening Balance'), ('OTHER', 'Other')], max_length=50)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('adjustment_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('adjusted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.lot')),
            ],
            options={
                'verbose_name': 'historical stock adjustment',
                'verbose_name_plural': 'historical stock adjustments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delta', models.IntegerField()),
                ('qty_before', models.PositiveIntegerField()),
                ('qty_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('NOT_FOUND', 'Not Found'), ('SPOILAGE', 'Spoilage'), ('COUNT_CORRECTION', 'Count Correction'), ('FOUND_EXTRA', 'Found Extra'), ('MIGRATION_OPENING_BALANCE', 'Migration Opening Balance'), ('OTHER', 'Other')], max_length=50)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('adjustment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.lot')),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
    ]
