# Generated by Django 6.0.7 on 2026-08-02 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_stockadjustment_adjusted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.commodity')),
            ],
            options={
                'verbose_name': 'Commodity Alias',
                'verbose_name_plural': 'Commodity Aliases',
                'constraints': [models.UniqueConstraint(fields=('commodity', 'name'), name='unique_commodity_alias')],
            },
        ),
    ]
