# Generated by Django 6.0.7 on 2026-08-07 13:56

import re
from django.db import migrations


def rename_legacy_lots(apps, schema_editor):
    Lot = apps.get_model('inventory', 'Lot')
    Sequence = apps.get_model('inventory', 'Sequence')
    from libs.lot_numbers import build_lot_number

    legacy_pattern = re.compile(r'^LOT-\d+$')

    for lot in Lot.objects.all():
        if legacy_pattern.match(lot.lot_number):
            receipt_date = lot.grn.receipt_date

            seq, created = Sequence.objects.get_or_create(
                facility=lot.facility,
                sequence_type='LOT_SERIAL',
                defaults={'prefix': '', 'current_value': 2606}
            )
            if not created and seq.current_value == 0:
                seq.current_value = 2606

            seq.current_value += 1
            seq.save(update_fields=['current_value'])

            new_lot_number, _warning = build_lot_number(
                receipt_date=receipt_date,
                serial=seq.current_value,
                bags=lot.initial_qty
            )

            lot.lot_number = new_lot_number
            lot.save(update_fields=['lot_number'])


def reverse_rename_legacy_lots(apps, schema_editor):
    raise migrations.exceptions.IrreversibleMigration("Legacy lot numbers cannot be reconstructed.")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_historicallotratechange_lotratechange'),
    ]

    operations = [
        migrations.RunPython(rename_legacy_lots, reverse_rename_legacy_lots),
    ]
