<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import SelectButton from 'primevue/selectbutton'
import DatePicker from 'primevue/datepicker'
import { Plus, Trash2, FileCheck } from 'lucide-vue-next'
import { formatQty, formatCurrency } from '../../utils/format'
import { useDeliveryNoteForm } from '../../composables/useDeliveryNoteForm'
import { useLotList } from '../../composables/useLots'
import type { PartyOutput } from '../../api/party'

interface Props {
  facilityId: number | undefined
  parties: PartyOutput[]
  loadingParties?: boolean
}

const props = defineProps<Props>()

const emit = defineEmits<{
  close: []
  created: [dnNumber: string, status: string]
}>()

const { t } = useI18n()
const facilityIdRef = computed(() => props.facilityId)

const chargeModeOptions = computed(() => [
  { label: t('chargeMode.FLAT'), value: 'FLAT' },
  { label: t('chargeMode.PER_UNIT'), value: 'PER_UNIT' }
])

// Fetch active in-stock lots for the selected facility
const lotsQuery = useLotList(facilityIdRef, computed(() => ({ inStockOnly: true })))
const availableLots = computed(() => lotsQuery.data.value || [])

const {
  party_id,
  partyIdProps,
  dispatch_date,
  dispatchDateProps,
  vehicle_number,
  vehicleNoProps,
  driver_name,
  driverNameProps,
  remarks,
  remarksProps,
  loading_charge_mode,
  loading_charge,
  loadingChargeProps,
  loading_unloading_rate_per_unit,
  loadingRateProps,
  lines,
  errors,
  addLineRow,
  removeLineRow,
  totalQty,
  computedDeliveryChargeEstimate,
  getLotAvailable,
  getLineQtyError,
  hasQtyExceeded,
  submitForm,
  isSubmitting
} = useDeliveryNoteForm(facilityIdRef, availableLots, (dnNumber, status) => emit('created', dnNumber, status))

// Filter lots by selected party if party is selected
const filteredLots = computed(() => {
  if (!party_id.value) return availableLots.value
  return availableLots.value.filter((l) => l.party_id === party_id.value)
})

const lotOptions = computed(() => {
  return filteredLots.value.map((l) => ({
    label: `${l.lot_number} - ${l.commodity_name || 'Item'} (${l.remaining_qty} ${l.commodity_unit || 'Bags'} avail)`,
    value: l.id
  }))
})
</script>

<template>
  <div class="detail-split-panel">
    <!-- Panel Header -->
    <div class="panel-topbar">
      <div class="breadcrumb-context">
        <span class="muted-crumb">{{ t('nav.delivery') }}</span>
        <span class="slash-crumb">></span>
        <span class="active-crumb">{{ t('delivery.createDeliveryNote') }}</span>
      </div>

      <div class="panel-actions">
        <button class="btn-text" type="button" @click="emit('close')">{{ t('common.cancel') }}</button>
        <button
          class="btn-outlined"
          type="button"
          :disabled="isSubmitting || hasQtyExceeded"
          @click="submitForm('DRAFT')"
        >
          {{ t('common.saveDraft') }}
        </button>
        <button
          class="btn-primary"
          type="button"
          :disabled="isSubmitting || hasQtyExceeded"
          @click="submitForm('POSTED')"
        >
          <FileCheck :size="16" />
          <span>{{ t('delivery.saveAndPost') }}</span>
        </button>
      </div>
    </div>

    <!-- Panel Form Scrollable Body -->
    <div class="panel-body">
      <!-- Header Grid Inputs -->
      <div class="form-grid">
        <div class="form-group">
          <label class="form-label">{{ t('delivery.dispatchDate') }} <span class="req">*</span></label>
          <DatePicker
            v-model="dispatch_date"
            v-bind="dispatchDateProps"
            dateFormat="dd/mm/yy"
            showIcon
            class="w-full"
            :invalid="!!errors.dispatch_date"
          />
          <small v-if="errors.dispatch_date" class="field-error">{{ errors.dispatch_date }}</small>
        </div>

        <div class="form-group">
          <label class="form-label">{{ t('delivery.deliveryNumber') }}</label>
          <InputText
            :value="t('grn.autoGenerated')"
            disabled
            class="w-full"
          />
        </div>

        <div class="form-group">
          <label class="form-label">{{ t('delivery.customerParty') }} <span class="req">*</span></label>
          <Select
            v-model="party_id"
            v-bind="partyIdProps"
            :options="props.parties"
            optionLabel="name"
            optionValue="id"
            :placeholder="t('parties.title')"
            :loading="props.loadingParties"
            class="w-full"
            :invalid="!!errors.party_id"
          />
          <small v-if="errors.party_id" class="field-error">{{ errors.party_id }}</small>
        </div>

        <div class="form-group">
          <label class="form-label">{{ t('delivery.driverName') }}</label>
          <InputText
            v-model="driver_name"
            v-bind="driverNameProps"
            :placeholder="t('delivery.driverName')"
            class="w-full"
          />
        </div>

        <div class="form-group">
          <label class="form-label">{{ t('delivery.vehicleNo') }}</label>
          <InputText
            v-model="vehicle_number"
            v-bind="vehicleNoProps"
            placeholder="e.g. GJ 05 AB 1234"
            class="w-full"
          />
        </div>

        <div class="form-group">
          <label class="form-label">{{ t('common.remarks') }}</label>
          <InputText
            v-model="remarks"
            v-bind="remarksProps"
            :placeholder="t('common.remarks')"
            class="w-full"
          />
        </div>
      </div>

      <!-- Delivery Charge Section -->
      <div class="charge-section-card">
        <div class="charge-header">
          <h4 class="section-subtitle">{{ t('delivery.loadingUnloadingCharge') }}</h4>
          <span class="charge-help">{{ t('delivery.loadingUnloadingHelp') }}</span>
        </div>

        <div class="charge-controls">
          <div class="form-group">
            <label class="form-label">{{ t('delivery.chargeMode') }}</label>
            <SelectButton
              v-model="loading_charge_mode"
              :options="chargeModeOptions"
              optionLabel="label"
              optionValue="value"
              :allowEmpty="false"
              class="w-full"
            />
          </div>

          <div v-if="loading_charge_mode === 'FLAT'" class="form-group">
            <label class="form-label">{{ t('delivery.flatLoadingUnloadingCharge') }}</label>
            <InputText
              v-model="loading_charge"
              v-bind="loadingChargeProps"
              placeholder="e.g. 500.00"
              class="w-full"
            />
          </div>

          <div v-else class="form-group">
            <label class="form-label">{{ t('delivery.loadingUnloadingRatePerUnit') }}</label>
            <InputText
              v-model="loading_unloading_rate_per_unit"
              v-bind="loadingRateProps"
              placeholder="e.g. 5.00"
              class="w-full"
            />
          </div>

          <div class="form-group est-display">
            <label class="form-label">{{ t('delivery.estimatedLoadingUnloadingCharge') }}</label>
            <span class="est-value">{{ formatCurrency(computedDeliveryChargeEstimate) }}</span>
          </div>
        </div>
      </div>

      <!-- Lines Section -->
      <div class="items-section">
        <h4 class="section-subtitle">{{ t('delivery.deliveryItems') }}</h4>

        <div class="items-table-wrapper">
          <table class="items-table">
            <thead>
              <tr>
                <th width="35">#</th>
                <th>{{ t('delivery.availableLot') }} <span class="req">*</span></th>
                <th width="120">{{ t('delivery.availableStock') }}</th>
                <th width="120">{{ t('delivery.dispatchQty') }} <span class="req">*</span></th>
                <th width="45"></th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(line, idx) in lines" :key="idx">
                <td>{{ idx + 1 }}</td>
                <td>
                  <Select
                    v-model="line.lot_id"
                    :options="lotOptions"
                    optionLabel="label"
                    optionValue="value"
                    :placeholder="t('common.select')"
                    :loading="lotsQuery.isLoading.value"
                    class="w-full input-sm-select"
                  />
                  <small v-if="getLineQtyError(idx)" class="field-error block mt-1">
                    {{ getLineQtyError(idx) }}
                  </small>
                </td>
                <td>
                  <span class="num-val">
                    {{ getLotAvailable(line.lot_id) !== null ? formatQty(getLotAvailable(line.lot_id)!, 0) : '-' }}
                  </span>
                </td>
                <td>
                  <input
                    type="number"
                    min="1"
                    v-model.number="line.qty"
                    class="p-inputtext p-component w-full input-sm num-align"
                    :class="{ 'p-invalid': getLineQtyError(idx) !== null }"
                  />
                </td>
                <td>
                  <button
                    class="icon-btn danger-hover"
                    type="button"
                    @click="removeLineRow(idx)"
                    :title="t('common.delete')"
                  >
                    <Trash2 :size="15" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <button class="btn-outlined add-item-btn" type="button" @click="addLineRow">
          <Plus :size="15" />
          <span>{{ t('delivery.addLineItem') }}</span>
        </button>
      </div>
    </div>

    <!-- Pinned Totals Summary Bar at Bottom -->
    <div class="panel-totals-bar">
      <div class="total-metric highlight-metric">
        <span class="metric-label">{{ t('delivery.totalDispatchQty') }}</span>
        <span class="metric-value">{{ formatQty(totalQty, 0) }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.detail-split-panel {
  flex: 1.5;
  background: var(--bg-surface);
  border: 1px solid var(--border-subtle);
  border-radius: 16px;
  box-shadow: var(--shadow-card);
  display: flex;
  flex-direction: column;
  height: calc(100vh - 120px);
  height: calc(100dvh - 120px);
  position: sticky;
  top: 88px;
  overflow: hidden;
}
.panel-topbar {
  padding: 16px 20px;
  border-bottom: 1px solid var(--border-subtle);
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: var(--bg-surface);
}
.breadcrumb-context {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13.5px;
}
.muted-crumb {
  color: var(--text-secondary);
  font-weight: 500;
}
.slash-crumb {
  color: var(--text-secondary);
}
.active-crumb {
  color: var(--text-primary);
  font-weight: 700;
}
.panel-actions {
  display: flex;
  align-items: center;
  gap: 10px;
}
.panel-body {
  flex: 1;
  padding: 20px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 20px;
}
.form-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}
.form-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.form-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-secondary);
}
.req {
  color: var(--status-danger-color);
}
.w-full {
  width: 100%;
}
.field-error {
  color: var(--status-danger-color);
  font-size: 11.5px;
}
.charge-section-card {
  background: var(--bg-surface-hover);
  border: 1px solid var(--border-subtle);
  border-radius: 12px;
  padding: 14px 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.charge-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.charge-help {
  font-size: 12px;
  color: var(--text-secondary);
}
.charge-controls {
  display: grid;
  grid-template-columns: 1.2fr 1fr 1fr;
  gap: 16px;
  align-items: end;
}
.est-display {
  background: var(--bg-page);
  border: 1px solid var(--border-subtle);
  border-radius: 8px;
  padding: 8px 12px;
}
.est-value {
  font-size: 16px;
  font-weight: 700;
  color: var(--accent-primary);
}
.items-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.section-subtitle {
  font-size: 14px;
  font-weight: 700;
  color: var(--text-primary);
}
.items-table-wrapper {
  border: 1px solid var(--border-subtle);
  border-radius: 10px;
  overflow-x: auto;
}
.items-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12.5px;
  min-width: 600px;
}
.items-table th {
  background: var(--bg-page);
  padding: 10px 8px;
  text-align: left;
  font-weight: 600;
  color: var(--text-secondary);
  border-bottom: 1px solid var(--border-subtle);
}
.items-table td {
  padding: 6px 8px;
  border-bottom: 1px solid var(--border-subtle);
}
.input-sm {
  font-size: 12px !important;
  padding: 6px 8px !important;
  border-radius: 6px !important;
}
.input-sm-select {
  font-size: 12px !important;
}
.num-align {
  text-align: right;
}
.add-item-btn {
  align-self: flex-start;
  font-size: 12.5px;
  padding: 7px 14px;
}
.panel-totals-bar {
  padding: 16px 24px;
  border-top: 1px solid var(--border-subtle);
  background: var(--bg-sidebar);
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 36px;
}
.total-metric {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}
.metric-label {
  font-size: 11px;
  color: var(--text-secondary);
  font-weight: 600;
  text-transform: uppercase;
}
.metric-value {
  font-size: 18px;
  font-weight: 700;
  color: var(--text-primary);
  font-feature-settings: "tnum";
}
.highlight-metric .metric-value {
  color: var(--accent-primary);
  font-size: 20px;
}
@media (max-width: 900px) {
  .detail-split-panel {
    position: fixed;
    inset: 0;
    z-index: 1000;
    width: 100%;
    max-width: none;
    height: 100vh;
    height: 100dvh;
    border: none;
    border-radius: 0;
  }
}
@media (max-width: 768px) {
  .form-grid {
    grid-template-columns: 1fr;
  }
  .charge-controls {
    grid-template-columns: 1fr;
  }
  .panel-topbar {
    flex-wrap: wrap;
    gap: 12px;
  }
  .panel-actions {
    width: 100%;
    justify-content: flex-end;
  }
  .panel-totals-bar {
    justify-content: space-between;
    gap: 16px;
  }
}
</style>
