allowBuilds:
  esbuild: true
  sharp: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@vue/devtools-core@8.2.1'
  - '@vue/devtools-kit@8.2.1'
  - '@vue/devtools-shared@8.2.1'
  - vite-plugin-vue-devtools@8.2.1
  - eslint@10.8.0
