# Generated by Django 6.0.7 on 2026-07-25 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_seed_default_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='facility',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='factory_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN (e.g. 27ABCDE1234F1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='facility',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
