# Generated by Django 6.0.7 on 2026-08-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_bank_account_no_facility_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
