# Generated by Django 6.0.7 on 2026-08-01 00:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='default_gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
    ]
