[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.7",
    "django-cors-headers>=4.9.0",
    "django-filter>=26.1",
    "django-simple-history>=3.13.0",
    "djangorestframework>=3.17.1",
    "drf-spectacular>=0.30.0",
    "gunicorn>=26.0.0",
    "psycopg[binary]>=3.3.4",
    "python-decouple>=3.8",
    "weasyprint>=69.0",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-django>=4.12.0",
]
