# Generated by Django 6.0.7 on 2026-07-25 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparty',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN (e.g. 27ABCDE1234F1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='party',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN (e.g. 27ABCDE1234F1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GSTIN'),
        ),
    ]
