# Generated by Django 6.0.7 on 2026-08-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_historicalparty_gstin_party_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparty',
            name='gst_registration_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('COMPOSITION', 'Composition'), ('UNREGISTERED', 'Unregistered'), ('CONSUMER', 'Consumer')], default='UNREGISTERED', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='party',
            name='gst_registration_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('COMPOSITION', 'Composition'), ('UNREGISTERED', 'Unregistered'), ('CONSUMER', 'Consumer')], default='UNREGISTERED', max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
