# Generated by Django 6.0.7 on 2026-07-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('facilities', '0003_facility_bank_account_no_facility_bank_ifsc_and_more'),
        ('inventory', '0004_grn_loading_charge_historicalgrn_loading_charge'),
        ('parties', '0002_historicalparty_gstin_party_gstin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratecard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalratecard',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.party'),
        ),
        migrations.AddField(
            model_name='historicalrentrun',
            name='chamber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalrentrun',
            name='commodity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.commodity'),
        ),
        migrations.AddField(
            model_name='historicalrentrun',
            name='min_billing_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalrentrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalrentrun',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.party'),
        ),
        migrations.AddField(
            model_name='historicalrentrun',
            name='pdf_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards', to='parties.party'),
        ),
        migrations.AddField(
            model_name='rentrun',
            name='chamber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rentrun',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_runs', to='inventory.commodity'),
        ),
        migrations.AddField(
            model_name='rentrun',
            name='min_billing_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentrun',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_runs', to='parties.party'),
        ),
        migrations.AddField(
            model_name='rentrun',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='rent_runs/'),
        ),
        migrations.AddConstraint(
            model_name='ratecard',
            constraint=models.UniqueConstraint(condition=models.Q(('party__isnull', True)), fields=('facility', 'commodity', 'weight_category', 'effective_from'), name='uniq_default_rate_card'),
        ),
        migrations.AddConstraint(
            model_name='ratecard',
            constraint=models.UniqueConstraint(condition=models.Q(('party__isnull', False)), fields=('facility', 'party', 'commodity', 'weight_category', 'effective_from'), name='uniq_party_rate_card'),
        ),
    ]
