# Generated by Django 6.0.7 on 2026-07-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_ratecard_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrentrun',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='rentrun',
            name='pdf_file',
        ),
    ]
