# Generated by Django 6.0.7 on 2026-07-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_historicalrentrun_pdf_file_and_more'),
        ('invoicing', '0003_remove_historicalinvoice_rent_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalratecard',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='historicalratecard',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='historicalratecard',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalratecard',
            name='party',
        ),
        migrations.RemoveField(
            model_name='historicalrentrun',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='historicalrentrun',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='historicalrentrun',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrentrun',
            name='party',
        ),
        migrations.RemoveConstraint(
            model_name='ratecard',
            name='uniq_default_rate_card',
        ),
        migrations.RemoveConstraint(
            model_name='ratecard',
            name='uniq_party_rate_card',
        ),
        migrations.RemoveField(
            model_name='rentrun',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='rentrun',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='rentrun',
            name='party',
        ),
        migrations.AlterUniqueTogether(
            name='rentrunline',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rentrunline',
            name='rent_run',
        ),
        migrations.RemoveField(
            model_name='rentrunline',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='rentrunline',
            name='party',
        ),
        migrations.DeleteModel(
            name='HistoricalRateCard',
        ),
        migrations.DeleteModel(
            name='HistoricalRentRun',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='party',
        ),
        migrations.DeleteModel(
            name='RentRun',
        ),
        migrations.DeleteModel(
            name='RentRunLine',
        ),
        migrations.DeleteModel(
            name='RateCard',
        ),
    ]
