# Generated by Django 6.0.7 on 2026-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='balance_after',
            field=models.PositiveIntegerField(blank=True, help_text='Lot remaining_qty immediately AFTER this line was posted (paper form Balance column). NULL for draft lines.', null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_notes/'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='transporter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldeliveryline',
            name='balance_after',
            field=models.PositiveIntegerField(blank=True, help_text='Lot remaining_qty immediately AFTER this line was posted (paper form Balance column). NULL for draft lines.', null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='pdf_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='transporter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
