# Generated by Django 6.0.7 on 2026-07-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryline_balance_after_deliverynote_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='historicaldeliverynote',
            name='pdf_file',
        ),
    ]
