# Generated by Django 6.0.7 on 2026-07-26 20:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_deliverynote_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='loading_charge_mode',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PER_UNIT', 'Per Unit')], default='FLAT', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='loading_unloading_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='loading_charge_mode',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PER_UNIT', 'Per Unit')], default='FLAT', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='loading_unloading_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
