# Generated by Django 6.0.7 on 2026-07-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverynote_loading_charge_and_more'),
        ('invoicing', '0003_remove_historicalinvoice_rent_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='invoicing.invoiceline'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='loading_charge_invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliveryline',
            name='invoice_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoicing.invoiceline'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryline',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='loading_charge_invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
