# Generated by Django 6.0.7 on 2026-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryline_invoice_line_deliveryline_invoiced_at_and_more'),
        ('facilities', '0003_facility_bank_account_no_facility_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='dn_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaldeliverynote',
            name='dn_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='deliverynote',
            unique_together={('facility', 'dn_number')},
        ),
    ]
