# Generated by Django 6.0.7 on 2026-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_deliverynote_dn_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
