# Generated by Django 6.0.7 on 2026-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverynote_last_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='legacy_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicaldeliverynote',
            name='legacy_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
