"""
This module provides views for accounting exports, specifically:
1. CSV Invoice Register: lists invoices and their details or lines in CSV format.
2. Tally XML Export: generates Tally-compatible XML for importing Sales vouchers.

WARNING: The Tally XML output generated by this module has NOT been tested against a real
Tally installation. The first import MUST be run against a COPY of the Tally company file,
never against the live books, to avoid any unintended data duplication or corruption.
"""

import csv
import xml.etree.ElementTree as ET
from decimal import Decimal, ROUND_HALF_UP
from django.http import HttpResponse
from django.utils.dateparse import parse_date
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import ValidationError
from drf_spectacular.utils import extend_schema, OpenApiParameter
from drf_spectacular.types import OpenApiTypes

from apps.facilities.models import Facility
from apps.invoicing.models import Invoice
from libs.fiscal import fy_label, state_code_from_gstin
from libs.renderers import CSVRenderer, XMLRenderer

# TALLY LEDGER CONFIGURATION
# These ledger names must match the exact ledger names that already exist in the
# destination Tally company, or Tally will create duplicate/new ledger accounts.
TALLY_LEDGER_CONFIG = {
    'charge_types': {
        'RENT': 'Warehouse Rent Income',
        'LOADING_UNLOADING': 'Loading and Unloading Income',
        'TRANSPORT': 'Transport Income',
        'WEIGHING': 'Weighing Income',
        'OTHER': 'Other Service Income',
    },
    'taxes': {
        'cgst': 'CGST Input/Output Ledger',
        'sgst': 'SGST Input/Output Ledger',
        'igst': 'IGST Input/Output Ledger',
    }
}


class InvoiceRegisterExportView(APIView):
    permission_classes = [IsAuthenticated]
    renderer_classes = [CSVRenderer]

    @extend_schema(
        parameters=[
            OpenApiParameter('facility', OpenApiTypes.STR, OpenApiParameter.QUERY, required=True, description="Facility ID or Facility Code"),
            OpenApiParameter('financial_year', OpenApiTypes.STR, OpenApiParameter.QUERY, required=False, description="Filter by Financial Year (e.g. 2026-27)"),
            OpenApiParameter('date_from', OpenApiTypes.DATE, OpenApiParameter.QUERY, required=False, description="Filter by invoice_date >= date_from"),
            OpenApiParameter('date_to', OpenApiTypes.DATE, OpenApiParameter.QUERY, required=False, description="Filter by invoice_date <= date_to"),
            OpenApiParameter('detail', OpenApiTypes.STR, OpenApiParameter.QUERY, required=False, default='summary', description="Level of detail: 'summary' or 'lines'"),
        ],
        responses={200: OpenApiTypes.BINARY},
        summary="Export Invoice Register to CSV"
    )
    def get(self, request):
        facility_val = request.query_params.get('facility')
        if not facility_val:
            raise ValidationError({"facility": "This query parameter is required."})

        try:
            # Try to resolve by ID
            facility = Facility.objects.get(id=int(facility_val))
        except (ValueError, Facility.DoesNotExist):
            # Try to resolve by Code
            try:
                facility = Facility.objects.get(code=facility_val)
            except Facility.DoesNotExist:
                raise ValidationError({"facility": f"Facility not found for identifier: {facility_val}"})

        financial_year = request.query_params.get('financial_year')
        date_from = request.query_params.get('date_from')
        date_to = request.query_params.get('date_to')
        detail = request.query_params.get('detail', 'summary').lower()

        # Only POSTED invoices are exported.
        qs = Invoice.objects.filter(facility=facility, status=Invoice.Status.POSTED)

        if financial_year:
            qs = qs.filter(financial_year=financial_year)
        if date_from:
            parsed_from = parse_date(date_from)
            if parsed_from is None:
                raise ValidationError({"date_from": "Must be a valid date (YYYY-MM-DD)."})
            qs = qs.filter(invoice_date__gte=parsed_from)
        if date_to:
            parsed_to = parse_date(date_to)
            if parsed_to is None:
                raise ValidationError({"date_to": "Must be a valid date (YYYY-MM-DD)."})
            qs = qs.filter(invoice_date__lte=parsed_to)

        qs = qs.order_by('invoice_date', 'id')

        # Determine FY suffix for filename
        if financial_year:
            fy_suffix = f"_{financial_year}"
        else:
            if date_from:
                d_from = parse_date(date_from)
                fy_suffix = f"_{fy_label(d_from)}" if d_from else ""
            elif qs.exists():
                latest_invoice = qs.order_by('-invoice_date').first()
                fy_suffix = f"_{fy_label(latest_invoice.invoice_date)}" if latest_invoice and latest_invoice.invoice_date else ""
            else:
                fy_suffix = "_all"

        response = HttpResponse(content_type='text/csv')

        if detail == 'lines':
            filename = f"invoice_register_lines_{facility.code}{fy_suffix}.csv"
            response['Content-Disposition'] = f'attachment; filename="{filename}"'

            writer = csv.writer(response)
            writer.writerow([
                "invoice_number",
                "invoice_date",
                "party_name",
                "party_gstin",
                "charge_type",
                "sac_code",
                "description",
                "quantity",
                "unit",
                "rate_per_unit",
                "period_from",
                "period_to",
                "amount"
            ])

            for inv in qs:
                party_name = inv.party_name_snapshot or (inv.party.name if inv.party else "")
                party_gstin = inv.party_gstin_snapshot or (inv.party.gstin if inv.party else "")

                for line in inv.lines.all().order_by('id'):
                    qty_str = line.quantity if line.quantity is not None else ""
                    rate_str = f"{line.rate_per_unit:.2f}" if line.rate_per_unit is not None else ""
                    p_from = line.period_from.strftime('%Y-%m-%d') if line.period_from else ""
                    p_to = line.period_to.strftime('%Y-%m-%d') if line.period_to else ""

                    writer.writerow([
                        inv.invoice_number,
                        inv.invoice_date.strftime('%Y-%m-%d'),
                        party_name,
                        party_gstin,
                        line.charge_type,
                        line.sac_code,
                        line.description,
                        qty_str,
                        line.unit or "",
                        rate_str,
                        p_from,
                        p_to,
                        f"{line.amount:.2f}"
                    ])
        else:
            filename = f"invoice_register_summary_{facility.code}{fy_suffix}.csv"
            response['Content-Disposition'] = f'attachment; filename="{filename}"'

            writer = csv.writer(response)
            writer.writerow([
                "invoice_number",
                "invoice_date",
                "financial_year",
                "document_type",
                "party_name",
                "party_gstin",
                "party_state_code",
                "place_of_supply",
                "subtotal",
                "discount",
                "taxable_value",
                "cgst_rate",
                "cgst_amount",
                "sgst_rate",
                "sgst_amount",
                "igst_rate",
                "igst_amount",
                "total_amount",
                "amount_paid",
                "amount_due",
                "is_reverse_charge",
                "exemption_reason"
            ])

            for inv in qs:
                party_name = inv.party_name_snapshot or (inv.party.name if inv.party else "")
                party_gstin = inv.party_gstin_snapshot or (inv.party.gstin if inv.party else "")
                party_state_code = state_code_from_gstin(party_gstin)

                writer.writerow([
                    inv.invoice_number,
                    inv.invoice_date.strftime('%Y-%m-%d'),
                    inv.financial_year,
                    inv.document_type,
                    party_name,
                    party_gstin,
                    party_state_code,
                    inv.place_of_supply,
                    f"{inv.subtotal:.2f}",
                    f"{inv.discount_amount:.2f}",
                    f"{inv.taxable_value:.2f}",
                    f"{inv.cgst_rate:.2f}",
                    f"{inv.cgst_amount:.2f}",
                    f"{inv.sgst_rate:.2f}",
                    f"{inv.sgst_amount:.2f}",
                    f"{inv.igst_rate:.2f}",
                    f"{inv.igst_amount:.2f}",
                    f"{inv.total_amount:.2f}",
                    f"{inv.amount_paid:.2f}",
                    f"{inv.amount_due:.2f}",
                    "Yes" if inv.is_reverse_charge else "No",
                    inv.exemption_reason
                ])

        return response


class TallyExportView(APIView):
    permission_classes = [IsAuthenticated]
    renderer_classes = [XMLRenderer]

    @extend_schema(
        parameters=[
            OpenApiParameter('facility', OpenApiTypes.STR, OpenApiParameter.QUERY, required=True, description="Facility ID or Facility Code"),
            OpenApiParameter('financial_year', OpenApiTypes.STR, OpenApiParameter.QUERY, required=False, description="Filter by Financial Year (e.g. 2026-27)"),
            OpenApiParameter('date_from', OpenApiTypes.DATE, OpenApiParameter.QUERY, required=False, description="Filter by invoice_date >= date_from"),
            OpenApiParameter('date_to', OpenApiTypes.DATE, OpenApiParameter.QUERY, required=False, description="Filter by invoice_date <= date_to"),
            OpenApiParameter('company_name', OpenApiTypes.STR, OpenApiParameter.QUERY, required=False, description="Override the Tally current company name"),
        ],
        responses={200: OpenApiTypes.BINARY},
        summary="Export Invoices to Tally XML"
    )
    def get(self, request):
        facility_val = request.query_params.get('facility')
        if not facility_val:
            raise ValidationError({"facility": "This query parameter is required."})

        try:
            facility = Facility.objects.get(id=int(facility_val))
        except (ValueError, Facility.DoesNotExist):
            try:
                facility = Facility.objects.get(code=facility_val)
            except Facility.DoesNotExist:
                raise ValidationError({"facility": f"Facility not found for identifier: {facility_val}"})

        financial_year = request.query_params.get('financial_year')
        date_from = request.query_params.get('date_from')
        date_to = request.query_params.get('date_to')
        company_override = request.query_params.get('company_name')

        company_name = company_override if company_override else facility.name

        # Only POSTED invoices are exported.
        qs = Invoice.objects.filter(facility=facility, status=Invoice.Status.POSTED)

        if financial_year:
            qs = qs.filter(financial_year=financial_year)
        if date_from:
            parsed_from = parse_date(date_from)
            if parsed_from is None:
                raise ValidationError({"date_from": "Must be a valid date (YYYY-MM-DD)."})
            qs = qs.filter(invoice_date__gte=parsed_from)
        if date_to:
            parsed_to = parse_date(date_to)
            if parsed_to is None:
                raise ValidationError({"date_to": "Must be a valid date (YYYY-MM-DD)."})
            qs = qs.filter(invoice_date__lte=parsed_to)

        qs = qs.order_by('invoice_date', 'id')

        # Determine FY suffix for filename
        if financial_year:
            fy_suffix = f"_{financial_year}"
        else:
            if date_from:
                d_from = parse_date(date_from)
                fy_suffix = f"_{fy_label(d_from)}" if d_from else ""
            elif qs.exists():
                latest_invoice = qs.order_by('-invoice_date').first()
                fy_suffix = f"_{fy_label(latest_invoice.invoice_date)}" if latest_invoice and latest_invoice.invoice_date else ""
            else:
                fy_suffix = "_all"

        # Construct XML Document
        envelope = ET.Element('ENVELOPE')

        header = ET.SubElement(envelope, 'HEADER')
        tallyrequest = ET.SubElement(header, 'TALLYREQUEST')
        tallyrequest.text = 'Import Data'

        body = ET.SubElement(envelope, 'BODY')
        importdata = ET.SubElement(body, 'IMPORTDATA')

        requestdesc = ET.SubElement(importdata, 'REQUESTDESC')
        reportname = ET.SubElement(requestdesc, 'REPORTNAME')
        reportname.text = 'Vouchers'

        staticvariables = ET.SubElement(requestdesc, 'STATICVARIABLES')
        svcurrentcompany = ET.SubElement(staticvariables, 'SVCURRENTCOMPANY')
        svcurrentcompany.text = company_name

        requestdata = ET.SubElement(importdata, 'REQUESTDATA')

        for inv in qs:
            tallymessage = ET.SubElement(requestdata, 'TALLYMESSAGE')
            tallymessage.set('xmlns:UDF', 'TallyUDF')

            voucher = ET.SubElement(tallymessage, 'VOUCHER')
            voucher.set('VCHTYPE', 'Sales')
            voucher.set('ACTION', 'Create')
            voucher.set('OBJVIEW', 'Invoice Voucher View')

            # Standard voucher metadata
            v_date = ET.SubElement(voucher, 'DATE')
            v_date.text = inv.invoice_date.strftime('%Y%m%d')

            v_typename = ET.SubElement(voucher, 'VOUCHERTYPENAME')
            v_typename.text = 'Sales'

            v_number = ET.SubElement(voucher, 'VOUCHERNUMBER')
            v_number.text = inv.invoice_number

            v_reference = ET.SubElement(voucher, 'REFERENCE')
            v_reference.text = inv.invoice_number

            party_name = inv.party_name_snapshot or (inv.party.name if inv.party else "")
            v_partyname = ET.SubElement(voucher, 'PARTYLEDGERNAME')
            v_partyname.text = party_name

            # Generate ledger entries:
            # - Debit the Party Ledger with total_amount
            # - Credit the respective Income Ledgers for charge_types
            # - Credit the Tax Ledgers (CGST/SGST/IGST) if non-zero
            entries = []

            # 1. Party Ledger (DEBIT)
            entries.append({
                'ledger_name': party_name,
                'is_deemed_positive': 'Yes',
                'amount': inv.total_amount  # Positive amount represents a Debit in Tally XML Sales Voucher
            })

            # Gather and aggregate line amounts by charge_type
            income_by_charge = {}
            for line in inv.lines.all():
                income_by_charge[line.charge_type] = income_by_charge.get(line.charge_type, Decimal('0.00')) + line.amount

            # If there is a discount_amount, adjust the charge type amounts proportionally so they sum to taxable_value.
            # This balances the voucher since total_amount = taxable_value + cgst + sgst + igst.
            subtotal = inv.subtotal
            taxable_value = inv.taxable_value
            adjusted_incomes = {}

            if subtotal > 0:
                ratio = taxable_value / subtotal
            else:
                ratio = Decimal('1.00')

            for ct, amt in income_by_charge.items():
                adjusted_incomes[ct] = (amt * ratio).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

            # Check and correct for any rounding discrepancy
            allocated_income = sum(adjusted_incomes.values(), Decimal('0.00'))
            taxes_sum = inv.cgst_amount + inv.sgst_amount + inv.igst_amount
            discrepancy = inv.total_amount - (allocated_income + taxes_sum)

            if discrepancy != 0 and adjusted_incomes:
                # Add the discrepancy to the largest income entry to ensure perfect balance
                largest_ct = max(adjusted_incomes, key=adjusted_incomes.get)
                adjusted_incomes[largest_ct] += discrepancy

            # 2. Income Ledgers (CREDIT)
            for ct, amt in adjusted_incomes.items():
                if amt != 0:
                    ledger_name = TALLY_LEDGER_CONFIG['charge_types'].get(ct, 'Other Service Income')
                    entries.append({
                        'ledger_name': ledger_name,
                        'is_deemed_positive': 'No',
                        'amount': -amt  # Negative amount represents a Credit in Tally XML Sales Voucher
                    })

            # 3. Tax Ledgers (CREDIT)
            tax_components = [
                ('cgst', inv.cgst_amount),
                ('sgst', inv.sgst_amount),
                ('igst', inv.igst_amount),
            ]
            for tax_key, tax_amt in tax_components:
                if tax_amt != 0:
                    ledger_name = TALLY_LEDGER_CONFIG['taxes'].get(tax_key, f"{tax_key.upper()} Ledger")
                    entries.append({
                        'ledger_name': ledger_name,
                        'is_deemed_positive': 'No',
                        'amount': -tax_amt  # Negative amount represents a Credit in Tally XML Sales Voucher
                    })

            # DEBIT / CREDIT SIGN CONVENTION IN TALLY XML:
            # - Debit entries (increases in assets/debit, e.g., the Party Ledger entry for total receivable amount)
            #   have a positive amount and <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>.
            # - Credit entries (increases in revenue/credit, e.g., Income Ledgers for charge types, and Tax Ledgers for CGST/SGST/IGST)
            #   have a negative amount and <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>.
            # The sum of all entries' amounts in a voucher balances to exactly zero algebraically.
            for entry in entries:
                ledger_entry = ET.SubElement(voucher, 'ALLLEDGERENTRIES.LIST')

                ledger_name_el = ET.SubElement(ledger_entry, 'LEDGERNAME')
                ledger_name_el.text = entry['ledger_name']

                is_deemed_pos_el = ET.SubElement(ledger_entry, 'ISDEEMEDPOSITIVE')
                is_deemed_pos_el.text = entry['is_deemed_positive']

                amount_el = ET.SubElement(ledger_entry, 'AMOUNT')
                amount_el.text = f"{entry['amount']:.2f}"

        # Serialize XML
        xml_bytes = ET.tostring(envelope, encoding='utf-8', xml_declaration=True)

        filename = f"tally_export_{facility.code}{fy_suffix}.xml"
        response = HttpResponse(xml_bytes, content_type='application/xml')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response
